### ISSUE TITLE
[Bug] [PRE-PROD] Cannot upload files > 1 MB

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#156]
Expectation: I can upload files that are not bigger than my remaining quota 

https://github.com/linagora/twake-drive/assets/97684890/8af5ca24-1794-43e3-a3bc-cd2f548916cc

**Comment by tk-nguyen** [comment]
Default nginx client body size is 1 MB: https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

Relevant configuration:
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-body-size

cc @nghiant2709

**Comment by nghiant2709** [comment]
Since the k8s default nginx client body size is 1 MB, we need to set `proxy-body-size: 200m` to match with tdrive nginx config
- https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/56
- https://github.com/linagora/twake-drive/blob/main/tdrive/docker/tdrive-frontend/nginx.conf#L12
