### ISSUE TITLE
[Bug] The Next button is inactive

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-workplace#70]
1. Open https://register.tom-dev.xyz
2. Enter a correct phone number 
3. The Next button is inactive for around 1-2 minutes. It only becomes visually active after a very long time, but it's still impossible to click it

https://github.com/linagora/twake-workplace/assets/97684890/df086c32-345f-4447-ab95-f5d32c2d058c

https://github.com/linagora/twake-workplace/assets/97684890/d725348b-762a-4acc-9aff-b73e2871844f

**Comment by rezk2ll** [comment]
this was due to temporary error when the LDAP service is not available. the app attempts to check the phone existance in LDAP but the server doesn't respond and times out.

 fixed in https://github.com/linagora/twake-workplace/commit/066beb61595aa9c09764677abc4ac0240ee8d1ce

the app will display an error when it can't connect to LDAP ( to check the phone ), and will resume when LDAP server is back.
